"""
Lists of words for the different difficulties
"""
easy_words = [
    'god',
    'leo',
    'sky',
    'sun',
    'holy',
    'mars',
    'moon',
    'nasa',
    'star',
    'void',
    'aries',
    'comet',
    'earth',
    'libra',
    'lunar',
    'lupus',
    'orion',
    'pluto',
    'space',
    'stars',
    'venus',
    'virgo',
    'angels',
    'astral',
    'aurora',
    'cancer',
    'cosmic',
    'cosmos',
    'crater',
    'divine',
    'galaxy',
    'gemini',
    'meteor',
    'nebula',
    'planet',
    'saturn',
    'sirius',
    'taurus',
    'uranus',
    'zodiac'
]

medium_words = [
    'ancient',
    'angelic',
    'eternal',
    'gravity',
    'heavens',
    'jupitar',
    'mercury',
    'neptune',
    'pegasus',
    'sputnik',
    'stellar',
    'aquarius',
    'ethereal',
    'galactic',
    'heavenly',
    'mystical',
    'orbiting',
    'scorpius',
    'solstice',
    'universe',
    'wormhole',
    'andromeda',
    'asteroids',
    'astrology',
    'astronaut',
    'capricorn',
    'centaurus',
    'cosmology',
    'horoscope',
    'meteoroid',
    'planetary',
    'radiation',
    'satellite',
    'spiritual',
    'starlight',
    'supernova',
    'cassiopeia',
]

hard_words = [
    'new moon',
    'black hole',
    'north star',
    'ursa major',
    'astronomers',
    'dwarf planet',
    'falling star',
    'sagittarius',
    'solar system',
    'terrestrial',
    'the milky way',
    'astronomical',
    'crescent moon',
    'interstellar',
    'meteor shower',
    'mythological',
    'shooting star',
    'solar eclipse',
    'space station',
    'spectroscope',
    'big bang theory',
    'constellation',
    'weightlessness',
    'hubble telescope',
    'celestiralsphere',
    'extraterrestrial',
    'celestial mechanics'
]
